---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    postgresql_backup_spec:
      - database_name: "database"
        database_user: "dbuser"
        database_password: "dbpassword"

  roles:
    - role: ansible_role_postgresql_backup
